addEmbeddableBadgeConfiguration(id: <string>, subject: <string>, status: <string>, color: <string>, animatedOverlayColor: <string>, link: <string>)

def win32BuildBadge = addEmbeddableBadgeConfiguration(id: "win32build", subject: "Windows Build")

pipeline {
	agent any
	environment {
    	SQ_TOKEN = credentials('aem-sonarqube-token')
    }
    parameters {
    	string(name: 'branch', defaultValue: 'master')
    }
	stages {
		stage('Clone sources') {
			steps {
				git credentialsId: '04f33554-fcb8-4fad-aafe-ef28648cbf42',
					url: 'https://github.com/urvashiarora/aem-poc.git',
					branch: params.branch
			}
		}
		stage('Sonarqube') {
			steps {
				   script {
                			win32BuildBadge.setStatus('running')
               				 try {
			    			sh "./gradlew -S -i clean sonarqube -Dsonar.login=${SQ_TOKEN}"
                    				win32BuildBadge.setStatus('passing')
                			} catch (Exception err) {
                    			win32BuildBadge.setStatus('failing')

                   			 win32BuildBadge.setColor('pink')

                    			error 'Build failed'
                			}
           			 }
			}
		}
	}
}

