pipeline {
	agent any
	environment {
    	SQ_TOKEN = credentials('aem-sonarqube-token')
    }
    parameters {
    	string(name: 'branch', defaultValue: 'master')
    }
	stages {
		stage('Clone sources') {
			steps {
				git credentialsId: '04f33554-fcb8-4fad-aafe-ef28648cbf42',
					url: 'https://github.com/urvashiarora/aem-poc.git',
					branch: params.branch
			}
		}
		stage('Sonarqube') {
			steps {
				sh "./gradlew -S -i clean sonarqube -Dsonar.login=${SQ_TOKEN}"
			}
		}
	}
}


